### ISSUE TITLE
Fix dependency versions

### ISSUE THREAD

**Issue by dimitry-ishenko** [jupyter-xeus/xeus-lua#19]
CMakeLists.txt currently says:

```
set(xeus_REQUIRED_VERSION 0.25.0)
```

but xeus 2.0~ is the minimum version required. (Tried compiling against 1.0~ and it also failed.)

Versions for other packages are likely out of date as well.

**Comment by DerThorsten** [comment]
https://github.com/jupyter-xeus/xeus-lua/pull/20 should hopefully fix this.

**Comment by DerThorsten** [comment]
feel free to re-open if there are any issues

**Comment by DerThorsten** [comment]
Atm all the widgets for xeus-lua are compiled in:
ie we need xwidgets and xcanvas for the Lua version of these widgets. But in the long run, these extension two should be a separate package that can be then be imported from Lua.
Compiling xeus-lua without xcanvas will just remove the canvas widget.
