### ISSUE TITLE
osx-arm64 builds

### ISSUE THREAD

**Issue by user799595** [jupyter-xeus/xeus-lua#34]
* Operating System: MacOS 12.6.1

### Description

Trying to install xeus-lua

### What I Did

```
mamba install -c conda-forge xeus-lua
....
Encountered problems while solving:
  - nothing provides requested xeus-lua
```

It looks like you might just need to add a line to
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt
See here for details:
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by JohanMabille** [comment]
The osx-arm63 build is now available, see https://github.com/conda-forge/xeus-lua-feedstock/pull/48
