### ISSUE TITLE
JupyterLite support

### ISSUE THREAD

**Issue by jtpio** [jupyter-xeus/xeus-lua#5]
### Description

As an alternative to https://github.com/jupyterlite/jupyterlite/pull/348, we should consider developing the `xeus-lua` kernel as a [federated serverlite extension](https://github.com/jupyterlite/jupyterlite/issues/104).

This means the kernel will not have to live in the main `jupyterlite` repo, and we could keep the complexity of building the wasm outside of it.

If we want to have more `xeus` based kernels share some code, maybe we could extract the common logic into a separate shared package. Then other kernels could depend on it. It's not clear yet how the full chain would work, but probably the worker file could for example be shared and the kernels can replace the URL to the wasm file on the fly.

Then we can package the kernel as a Python package, with the kernel files placed as static files under `PREFIX/share/jupyter/lite/extensions`. Folks can then install the kernel on their own JupyterLite site by cloning the [demo](https://github.com/jupyterlite/demo) and add `jupyterlite-xeus-lua` Python package to the `requirements.txt`.

**Comment by jtpio** [comment]
Once this is setup we can even have a JupyterLite website published to the ReadTheDocs of the `xeus-lua` repo directly.

**Comment by DerThorsten** [comment]
@jtpio sounds great! Anything I can do already to set up such an extension?

**Comment by jtpio** [comment]
We'll probably need https://github.com/jupyterlite/jupyterlite/pull/352 to land first. There we're taking the `p5-kernel` out of the main repo to put it under https://github.com/jupyterlite/p5-kernel. This should serve as a good reference / template for other kernels.

In the meantime maybe we can check how we could set up ReadTheDocs to host the JupyterLite website? There is some minimal documentation in https://jupyterlite.readthedocs.io/en/latest/deploying.html#readthedocs. There is also [ipydrawio](https://github.com/deathbeds/ipydrawio/blob/master/docs/conf.py) doing something similar. So we can double check we are able to continuously deploy to RTD, and also able to build the kernel assets on CI.

The alternative would to publish to the same repo on GitHub Pages. But this might increase the size of the repo quite a bit since the deployed assets are quite heavy at the moment (~20MB for the lite site and the `.wasm` files for xeus-lua)

**Comment by jtpio** [comment]
> but probably the worker file could for example be shared

When it comes to sharing logic between xeus based kernels, let's see how it goes but one way could be to have a shared package / plugin that the kernel extensions would depend on.

**Comment by DerThorsten** [comment]
@jtpio the difference between different xeus based kernels is basically just the filename of the emscripten generated  js / wasm files.

**Comment by jtpio** [comment]
> the difference between different xeus based kernels is basically just the filename of the emscripten generated js / wasm files.

That is really great :+1: 

So we could have the `@jupyterlite/xeus-kernel` part of https://github.com/jupyterlite/jupyterlite/pull/348 living in https://github.com/jupyterlite/xeus-kernel.

The `jupyterlite-xeus-lua` package would then define the `extension` (what currently corresponds to `@jupyterlite/xeus-kernel-extension`. It would provide the spec and the wasm / js files. It could live either in https://github.com/jupyterlite/xeus-lua or stay here in https://github.com/jupyter-xeus/xeus-lua.

**Comment by jtpio** [comment]
Also I'm wrapping up https://github.com/jupyterlite/serverlite-cookiecutter-ts/pull/1 so we can use the cookiecutter to bootstrap the `xeus-lua` repo.

**Comment by jtpio** [comment]
There is now an echo kernel in this repo: https://github.com/jupyterlite/echo-kernel

Which was generated from: https://github.com/jupyterlite/serverlite-cookiecutter-ts

Hopefully it should provide the basic structure for authoring kernels as JupyterLite server extension. If something is broken or doesn't look right, don't hesitate to open an issue or PR, thanks!

**Comment by jtpio** [comment]
Closing since `jupyterlite-xeus-lua` in now being developed in https://github.com/jupyterlite/xeus-lua-kernel and has been released. Thanks!
